# Generated by Django 5.1.15 on 2026-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_robot_webhook_enabled_alter_order_escrow_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnpayment',
            name='subaddress_index',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
